//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Project/InputSystem/GameControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameControls"",
    ""maps"": [
        {
            ""name"": ""Bird"",
            ""id"": ""b41cfe79-47b2-41c4-b486-dc6ce05b465f"",
            ""actions"": [
                {
                    ""name"": ""ScreenTap"",
                    ""type"": ""Value"",
                    ""id"": ""5ffcbab9-50f4-4423-b848-43915979275f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8caa618e-e835-4988-a082-9f420d8aea25"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ScreenTap"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Bird
        m_Bird = asset.FindActionMap("Bird", throwIfNotFound: true);
        m_Bird_ScreenTap = m_Bird.FindAction("ScreenTap", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Bird
    private readonly InputActionMap m_Bird;
    private List<IBirdActions> m_BirdActionsCallbackInterfaces = new List<IBirdActions>();
    private readonly InputAction m_Bird_ScreenTap;
    public struct BirdActions
    {
        private @GameControls m_Wrapper;
        public BirdActions(@GameControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @ScreenTap => m_Wrapper.m_Bird_ScreenTap;
        public InputActionMap Get() { return m_Wrapper.m_Bird; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BirdActions set) { return set.Get(); }
        public void AddCallbacks(IBirdActions instance)
        {
            if (instance == null || m_Wrapper.m_BirdActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_BirdActionsCallbackInterfaces.Add(instance);
            @ScreenTap.started += instance.OnScreenTap;
            @ScreenTap.performed += instance.OnScreenTap;
            @ScreenTap.canceled += instance.OnScreenTap;
        }

        private void UnregisterCallbacks(IBirdActions instance)
        {
            @ScreenTap.started -= instance.OnScreenTap;
            @ScreenTap.performed -= instance.OnScreenTap;
            @ScreenTap.canceled -= instance.OnScreenTap;
        }

        public void RemoveCallbacks(IBirdActions instance)
        {
            if (m_Wrapper.m_BirdActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IBirdActions instance)
        {
            foreach (var item in m_Wrapper.m_BirdActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_BirdActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public BirdActions @Bird => new BirdActions(this);
    public interface IBirdActions
    {
        void OnScreenTap(InputAction.CallbackContext context);
    }
}
